=== bpmn-io/moddle/resources/schema/moddle.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://bpmn.io/20241206/moddle-package.schema.json",
  "title": "Moddle Package Schema",
  "type": "object",
  "required": [
    "name",
    "prefix",
    "uri",
    "types"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of the package."
    },
    "$schema": {
      "type": "string",
      "description": "Reference to this schema"
    },
    "prefix": {
      "type": "string",
      "description": "The prefix uniquely identifies elements in a package if more multiple packages are in place."
    },
    "uri": {
      "type": "string",
      "description": "The uri field in a package definition defines the associated XML namespace URI."
    },
    "types": {
      "type": "array",
      "description": "List of types belonging to this package.",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the defined type."
          },
          "superClass": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Name of the super type."
            }
          },
          "isAbstract": {
            "type": "boolean",
            "description": "Can this type be instantiated."
          },
          "properties": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Name of the property."
                },
                "type": {
                  "type": "string",
                  "description": "Type of the property."
                },
                "isAttr": {
                  "type": "boolean",
                  "description": "Should the property be serialized as XML attribute."
                },
                "isBody": {
                  "type": "boolean",
                  "description": "Should the property be serialized as body element."
                },
                "isId": {
                  "type": "boolean",
                  "description": "Is current property map to XML node id."
                },
                "isMany": {
                  "type": "boolean",
                  "description": "Is the property an array or a single."
                },
                "isReference": {
                  "type": "boolean",
                  "description": "Is the property referencing to another element"
                },
                "default": {
                  "description": "Provides default for the property.",
                  "oneOf": [
                    {
                      "type": "boolean"
                    },
                    {
                      "type": "number"
                    },
                    {
                      "type": "string"
                    }
                  ]
                },
                "redefines": {
                  "type": "string",
                  "description": "Property name for the redefinition of existing property"
                },
                "replaces": {
                  "type": "string",
                  "description": "Property name for the replacement of existing property"
                },
                "xml": {
                  "type": "object",
                  "description": "Defines XML serialization details",
                  "properties": {
                    "serialize": {
                      "type": "string",
                      "description": "Provides XML serialization type, e.g. xsi:type"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "xml": {
      "type": "object",
      "description": "Defines XML serialization details.",
      "properties": {
        "tagAlias": {
          "const": "lowerCase"
        },
        "typePrefix": {
          "type": "string"
        }
      }
    },
    "associations": {
      "type": "array",
      "description": "The associations property is reserved for future use."
    },
    "enumerations": {
      "description": "The enumerations property is reserved for future use.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "literalValues": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== bpmn-io/moddle/test/fixtures/model/constraints.json
{
  "name": "Constraints",
  "uri": "https://constraints",
  "prefix": "cnstr",
  "types": [
    {
      "name": "Person",
      "properties": [
        {
          "name": "gender",
          "type": "String",
          "isAttr": true,
          "constraint": {
            "enum": [ "male", "female", "genderFluid" ]
          }
        },
        {
          "name": "age",
          "type": "Integer",
          "isAttr": true,
          "constraint": {
            "math": "0 <= x"
          }
        },
        {
          "name": "name",
          "type": "String",
          "isAttr": true,
          "constraint": {
            "regex": "^[A-Z][a-z]* [A-Z][a-z]*(-[A-Z][a-z]*)?$"
          }
        },
        {
          "name": "emails",
          "type": "String",
          "isBody": true,
          "isMany": true,
          "constraint": {
            "regex": "^.+@.+\\..+$"
          }
        },
        {
          "name": "Spouse",
          "type": "Person",
          "isBody": true,
          "constraint": {
            "enum": [ { "age": "10" } ]
          }
        }
      ]
    }
  ]
}

=== bpmn-io/moddle/test/fixtures/model/datatype.json
{
  "name": "DataTypes",
  "uri": "http://datatypes",
  "prefix": "dt",
  "types": [
    {
      "name": "Root",
      "properties": [
        { "name": "bounds", "serialize": "xsi:type", "type": "Rect" },
        { "name": "otherBounds",
          "type": "do:Rect",
          "serialize": "xsi:type",
          "isMany": true
        },
        {
          "name": "defaultSingle",
          "type": "Boolean",
          "default": true
        }
      ]
    },
    {
      "name": "Rect",
      "properties": [
        { "name": "y", "type": "Integer", "isAttr": true }
      ]
    }
  ]
}

=== bpmn-io/moddle/test/fixtures/model/extension/overlaps/camunda.json
{
  "name": "camunda",
  "prefix": "camunda",
  "uri": "http://camunda.org/schema/camunda/1.0",
  "xml": {
    "tagAlias": "lowerCase"
  },
  "associations": [],
  "types": [
    {
      "name": "TemplateSupported",
      "isAbstract": true,
      "extends": [
        "b:Root"
      ],
      "properties": [
        {
          "name": "modelerTemplate",
          "isAttr": true,
          "type": "String"
        }
      ]
    }
  ]
}

=== bpmn-io/moddle/test/fixtures/model/replaces/custom.json
{
  "name": "Replaces Extension",
  "uri": "http://replace-extension",
  "prefix": "c",
  "types": [
    {
      "name": "Base",
      "extends": [
        "b:Base"
      ],
      "properties": [
        { "name": "value", "type": "String" },
        { "name": "id", "type": "Integer", "replaces": "b:Base#id", "isId": true }
      ]
    }
  ]
}

=== bpmn-io/moddle/test/fixtures/model/replaces/extension.json
{
  "name": "Replaces Extension",
  "uri": "http://replace-extension",
  "prefix": "e",
  "types": [
    {
      "name": "Base",
      "superClass": [
        "b:Base"
      ],
      "properties": [
        { "name": "value", "type": "String" },
        { "name": "id", "type": "Integer", "replaces": "b:Base#id", "isId": true }
      ]
    }
  ]
}

=== bpmn-io/moddle/test/fixtures/model/redefines/extension.json
{
  "name": "Redefines Extension",
  "uri": "http://redefines-extension",
  "prefix": "e",
  "types": [
    {
      "name": "Base",
      "superClass": [
        "b:Base"
      ],
      "properties": [
        { "name": "value", "type": "String" },
        { "name": "id", "type": "Integer", "redefines": "b:Base#id", "isId": true }
      ]
    }
  ]
}

=== bpmn-io/moddle/test/fixtures/model/element.json
{
  "name": "Element",
  "uri": "http://element",
  "prefix": "e",
  "types": [
    {
      "name": "Element",
      "isAbstract": true,
      "properties": [
        { "name": "children", "type": "Element", "isMany": true }
      ]
    },
    {
      "name": "NamedElement",
      "superClass": [ "Element" ],
      "properties": [
        { "name": "name", "type": "String" }
      ]
    }
  ]
}

=== bpmn-io/moddle/test/fixtures/model/redefines/base.json
{
  "name": "Redefines Base",
  "uri": "http://redefine",
  "prefix": "b",
  "types": [
    {
      "name": "Base",
      "properties": [
        { "name": "id", "type": "Integer" },
        { "name": "name", "type": "String" }
      ]
    },
    {
      "name": "Extension",
      "superClass": [ "Base" ],
      "properties": [
        { "name": "value", "type": "String" },
        { "name": "id", "type": "Integer", "redefines": "Base#id", "isId": true }
      ]
    }
  ]
}
